/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.mcgill.mcb.pcingola.snpSql.gui;

import java.io.File;

import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileFilter;

import ca.mcgill.mcb.pcingola.fileIterator.VcfFileIterator;
import ca.mcgill.mcb.pcingola.snpSql.SnpSqlCmdCreate;
import ca.mcgill.mcb.pcingola.snpSql.SnpSqlCmdSql;
import ca.mcgill.mcb.pcingola.util.Gpr;
import ca.mcgill.mcb.pcingola.vcf.VcfEntry;

/**
 * SnpSql GUI
 * 
 * 
 * @author pcingola
 */
public class SnpSqlGui extends javax.swing.JFrame {

	static final int TABLE_ROWS = 1000;

	String vcfFileName;

	/**
	 * Creates new form SnpSqlGui
	 */
	public SnpSqlGui() {
		initComponents();

		JComboBox vars[] = { jComboBoxVar, jComboBoxVar1, jComboBoxVar2, jComboBoxVar3, jComboBoxVar4, jComboBoxVar5, jComboBoxVar6 };
		JTextField vals[] = { jTextFieldValue, jTextFieldValue1, jTextFieldValue2, jTextFieldValue3, jTextFieldValue4, jTextFieldValue5, jTextFieldValue6 };
		JComboBox rel[] = { null, jComboBoxRel1, jComboBoxRel2, jComboBoxRel3, jComboBoxRel4, jComboBoxRel5, jComboBoxRel6 };
		JComboBox ops[] = { jComboBoxOp, jComboBoxOp1, jComboBoxOp2, jComboBoxOp3, jComboBoxOp4, jComboBoxOp5, jComboBoxOp6 };

		this.vars = vars;
		this.vals = vals;
		this.rel = rel;
		this.ops = ops;

		jButtonQuery.setEnabled(false);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSplitPane1 = new javax.swing.JSplitPane();
		jPanel1 = new javax.swing.JPanel();
		jButtonQuery = new javax.swing.JButton();
		jComboBoxVar = new javax.swing.JComboBox();
		jComboBoxOp = new javax.swing.JComboBox();
		jTextFieldValue = new javax.swing.JTextField();
		jComboBoxVar1 = new javax.swing.JComboBox();
		jComboBoxOp1 = new javax.swing.JComboBox();
		jTextFieldValue1 = new javax.swing.JTextField();
		jComboBoxRel1 = new javax.swing.JComboBox();
		jComboBoxRel2 = new javax.swing.JComboBox();
		jComboBoxVar2 = new javax.swing.JComboBox();
		jComboBoxOp2 = new javax.swing.JComboBox();
		jTextFieldValue2 = new javax.swing.JTextField();
		jComboBoxRel3 = new javax.swing.JComboBox();
		jComboBoxVar3 = new javax.swing.JComboBox();
		jComboBoxOp3 = new javax.swing.JComboBox();
		jTextFieldValue3 = new javax.swing.JTextField();
		jComboBoxRel4 = new javax.swing.JComboBox();
		jComboBoxVar4 = new javax.swing.JComboBox();
		jComboBoxOp4 = new javax.swing.JComboBox();
		jTextFieldValue4 = new javax.swing.JTextField();
		jComboBoxRel5 = new javax.swing.JComboBox();
		jComboBoxVar5 = new javax.swing.JComboBox();
		jComboBoxOp5 = new javax.swing.JComboBox();
		jTextFieldValue5 = new javax.swing.JTextField();
		jComboBoxRel6 = new javax.swing.JComboBox();
		jComboBoxVar6 = new javax.swing.JComboBox();
		jComboBoxOp6 = new javax.swing.JComboBox();
		jTextFieldValue6 = new javax.swing.JTextField();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextAreaResults = new javax.swing.JTextArea();
		jProgressBar1 = new javax.swing.JProgressBar();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		openMenuItem = new javax.swing.JMenuItem();
		exitMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("SnpSql");

		jSplitPane1.setDividerSize(1);
		jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
		jSplitPane1.setResizeWeight(1.0);

		jButtonQuery.setText("Query");
		jButtonQuery.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButtonQueryActionPerformed(evt);
			}
		});

		jComboBoxVar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "entry.chrom", "entry.pos", "entry.id", "entry.ref", "entry.alt", "entry.qual", "entry.filter", "entry.info", "eff.effect", "eff.impact", "eff.funClass", "eff.codon", "eff.aa", "eff.aaLen", "eff.gene", "eff.bioType", "eff.coding", "eff.transcriptId", "eff.exonId" }));

		jComboBoxOp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "=", "!=", "<", "<=", ">", ">=", "LIKE", " " }));

		jComboBoxVar1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "entry.chrom", "entry.pos", "entry.id", "entry.ref", "entry.alt", "entry.qual", "entry.filter", "entry.info", "eff.effect", "eff.impact", "eff.funClass", "eff.codon", "eff.aa", "eff.aaLen", "eff.gene", "eff.bioType", "eff.coding", "eff.transcriptId", "eff.exonId" }));

		jComboBoxOp1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "=", "!=", "<", "<=", ">", ">=", "LIKE", " " }));

		jComboBoxRel1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "AND", "OR" }));

		jComboBoxRel2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "AND", "OR" }));

		jComboBoxVar2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "entry.chrom", "entry.pos", "entry.id", "entry.ref", "entry.alt", "entry.qual", "entry.filter", "entry.info", "eff.effect", "eff.impact", "eff.funClass", "eff.codon", "eff.aa", "eff.aaLen", "eff.gene", "eff.bioType", "eff.coding", "eff.transcriptId", "eff.exonId" }));

		jComboBoxOp2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "=", "!=", "<", "<=", ">", ">=", "LIKE", " " }));

		jComboBoxRel3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "AND", "OR" }));

		jComboBoxVar3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "entry.chrom", "entry.pos", "entry.id", "entry.ref", "entry.alt", "entry.qual", "entry.filter", "entry.info", "eff.effect", "eff.impact", "eff.funClass", "eff.codon", "eff.aa", "eff.aaLen", "eff.gene", "eff.bioType", "eff.coding", "eff.transcriptId", "eff.exonId" }));

		jComboBoxOp3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "=", "!=", "<", "<=", ">", ">=", "LIKE", " " }));

		jComboBoxRel4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "AND", "OR" }));

		jComboBoxVar4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "entry.chrom", "entry.pos", "entry.id", "entry.ref", "entry.alt", "entry.qual", "entry.filter", "entry.info", "eff.effect", "eff.impact", "eff.funClass", "eff.codon", "eff.aa", "eff.aaLen", "eff.gene", "eff.bioType", "eff.coding", "eff.transcriptId", "eff.exonId" }));

		jComboBoxOp4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "=", "!=", "<", "<=", ">", ">=", "LIKE", " " }));

		jComboBoxRel5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "AND", "OR" }));

		jComboBoxVar5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "entry.chrom", "entry.pos", "entry.id", "entry.ref", "entry.alt", "entry.qual", "entry.filter", "entry.info", "eff.effect", "eff.impact", "eff.funClass", "eff.codon", "eff.aa", "eff.aaLen", "eff.gene", "eff.bioType", "eff.coding", "eff.transcriptId", "eff.exonId" }));

		jComboBoxOp5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "=", "!=", "<", "<=", ">", ">=", "LIKE", " " }));

		jComboBoxRel6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "AND", "OR" }));

		jComboBoxVar6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "entry.chrom", "entry.pos", "entry.id", "entry.ref", "entry.alt", "entry.qual", "entry.filter", "entry.info", "eff.effect", "eff.impact", "eff.funClass", "eff.codon", "eff.aa", "eff.aaLen", "eff.gene", "eff.bioType", "eff.coding", "eff.transcriptId", "eff.exonId" }));

		jComboBoxOp6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "=", "!=", "<", "<=", ">", ">=", "LIKE", " " }));

		jTextAreaResults.setColumns(20);
		jTextAreaResults.setEditable(false);
		jTextAreaResults.setFont(new java.awt.Font("Monotype Sorts", 0, 12)); // NOI18N
		jTextAreaResults.setRows(5);
		jTextAreaResults.setTabSize(4);
		jScrollPane2.setViewportView(jTextAreaResults);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										jPanel1Layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jButtonQuery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGroup(
														jPanel1Layout
																.createSequentialGroup()
																.addGroup(
																		jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jComboBoxRel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxVar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jComboBoxVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE).addComponent(jTextFieldValue1)))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jComboBoxRel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxVar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldValue2))
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jComboBoxRel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxVar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldValue3))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jComboBoxRel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxVar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldValue4))
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jComboBoxRel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxVar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldValue5))
												.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jComboBoxRel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxVar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jComboBoxOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jTextFieldValue6))).addContainerGap()).addComponent(jScrollPane2));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jComboBoxVar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextFieldValue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxRel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jComboBoxVar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextFieldValue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxRel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jComboBoxVar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextFieldValue3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxRel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jComboBoxVar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextFieldValue4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxRel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jComboBoxVar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextFieldValue5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxRel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jComboBoxVar6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jTextFieldValue6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jComboBoxRel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButtonQuery).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)));

		jSplitPane1.setLeftComponent(jPanel1);
		jSplitPane1.setRightComponent(jProgressBar1);

		fileMenu.setMnemonic('f');
		fileMenu.setText("File");

		openMenuItem.setMnemonic('o');
		openMenuItem.setText("Open");
		openMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				openMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(openMenuItem);

		exitMenuItem.setMnemonic('x');
		exitMenuItem.setText("Exit");
		exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exitMenuItem);

		menuBar.add(fileMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jSplitPane1));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
		System.exit(0);
	}//GEN-LAST:event_exitMenuItemActionPerformed

	private void jButtonQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueryActionPerformed
		// Build query 
		String query = "";
		for (int i = 0; i < vars.length; i++) {
			String relStr = (rel[i] != null ? "" + rel[i].getSelectedItem() : "");
			String var = vars[i].getSelectedItem().toString();
			String op = ops[i].getSelectedItem().toString();
			String val = vals[i].getText();

			if (!relStr.startsWith("---") && !var.startsWith("---") && !op.startsWith("---") && !val.isEmpty()) query += "\t" + relStr + " ( " + vars[i].getSelectedItem() + " " + ops[i].getSelectedItem() + " '" + vals[i].getText() + "' ) ";
		}

		// Query database
		SnpSqlCmdSql snpSqlCmdSql = new SnpSqlCmdSql(vcfFileName, query);
		snpSqlCmdSql.run();
		jTextAreaResults.setText(snpSqlCmdSql.getResultsTxt());
		jTextAreaResults.setCaretPosition(0);

	}//GEN-LAST:event_jButtonQueryActionPerformed

	private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
		// Open file chooser
		final JFileChooser fc = new JFileChooser();

		// Only allow VCF files
		FileFilter fileFilter = new FileFilter() {

			@Override
			public boolean accept(File file) {
				if (file.isDirectory()) return true;
				int extIdx = file.getName().lastIndexOf('.');
				if (extIdx < 0) return false;
				String ext = file.getName().substring(extIdx);
				return ext.toLowerCase().equals(".vcf");
			}

			@Override
			public String getDescription() {
				return "VCF file";
			}
		};

		fc.addChoosableFileFilter(fileFilter);
		fc.setFileFilter(fileFilter);

		// Show file chooser dialog
		int returnVal = fc.showOpenDialog(this);

		// Pressed "OK"?
		if (returnVal == 0) {
			vcfFileName = fc.getSelectedFile().getAbsolutePath();
			openFile();
			jButtonQuery.setEnabled(true);
		}
	}//GEN-LAST:event_openMenuItemActionPerformed

	/**
	 * Open a VCF file.
	 * Build database if required
	 */
	void openFile() {
		createDatabase();
		readVcfFile();
	}

	/**
	 * Create database
	 */
	void createDatabase() {
		String dbDataFileName = vcfFileName + ".data";
		File dbFile = new File(dbDataFileName);
		if (!dbFile.exists()) {
			int result = JOptionPane.showConfirmDialog(this, "Database not found!\nPress OK to build databse for this file", "Need to build database", JOptionPane.OK_CANCEL_OPTION);
			if (result == JOptionPane.OK_OPTION) {
				// OK, try to build database
				Gpr.debug("Build database for: " + vcfFileName);
				boolean ok = createDatabaseWorker();
				if (ok) {
					JOptionPane.showMessageDialog(this, "Database built succesfully", "Database build", JOptionPane.INFORMATION_MESSAGE);
				} else {
					JOptionPane.showMessageDialog(this, "Error building database", "Error", JOptionPane.ERROR_MESSAGE);
					vcfFileName = null;
				}
			} else vcfFileName = null;
		}
	}

	/**
	 * Worked that creates database in background
	 * @return 
	 */
	boolean createDatabaseWorker() {
		JOptionPane messagePane = new JOptionPane("Creaint database\n Please wait...", JOptionPane.INFORMATION_MESSAGE);
		final JDialog dialog = messagePane.createDialog(this, "Building databse");

		SwingWorker sw = new SwingWorker<Boolean, Void>() {

			@Override
			protected Boolean doInBackground() throws Exception {
				try {
					SnpSqlCmdCreate sscreate = new SnpSqlCmdCreate();
					return sscreate.run(vcfFileName);
				} catch (Throwable t) {
					t.printStackTrace();
				}
				return false;
			}

			// this is called when background thread above has completed.
			protected void done() {
				dialog.dispose();
			};
		};
		sw.execute();

		// Show dialog while executing worker
		dialog.setVisible(true);

		try {
			boolean ok = (Boolean) sw.get(); // Get return value from database build
			return ok;
		} catch (Exception e) {
			;
		}

		return false;
	}

	/**
	 * Read VCF file and show it in table
	 */
	void readVcfFile() {
		StringBuilder sb = new StringBuilder();

		if (vcfFileName != null) {
			int rowCount = 1;
			VcfFileIterator vfi = new VcfFileIterator(vcfFileName);
			boolean header = true;
			for (VcfEntry ve : vfi) {
				if (header) {
					header = false;
					if (!vfi.getHeader().isEmpty()) sb.append(vfi.getHeader() + "\n");
				}

				sb.append(ve + "\n");
				if (rowCount++ >= TABLE_ROWS) {
					sb.append("--- WARNING: Only first " + TABLE_ROWS + " rows are shown --- ");
					break;
				}
			}
		}

		// Show 'truncatd" warning
		jTextAreaResults.setText(sb.toString());
		jTextAreaResults.setCaretPosition(0);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/*
		 * Set the Nimbus look and feel
		 */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SnpSqlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SnpSqlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SnpSqlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SnpSqlGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/*
		 * Create and display the form
		 */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new SnpSqlGui().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem exitMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JButton jButtonQuery;
	private javax.swing.JComboBox jComboBoxOp;
	private javax.swing.JComboBox jComboBoxOp1;
	private javax.swing.JComboBox jComboBoxOp2;
	private javax.swing.JComboBox jComboBoxOp3;
	private javax.swing.JComboBox jComboBoxOp4;
	private javax.swing.JComboBox jComboBoxOp5;
	private javax.swing.JComboBox jComboBoxOp6;
	private javax.swing.JComboBox jComboBoxRel1;
	private javax.swing.JComboBox jComboBoxRel2;
	private javax.swing.JComboBox jComboBoxRel3;
	private javax.swing.JComboBox jComboBoxRel4;
	private javax.swing.JComboBox jComboBoxRel5;
	private javax.swing.JComboBox jComboBoxRel6;
	private javax.swing.JComboBox jComboBoxVar;
	private javax.swing.JComboBox jComboBoxVar1;
	private javax.swing.JComboBox jComboBoxVar2;
	private javax.swing.JComboBox jComboBoxVar3;
	private javax.swing.JComboBox jComboBoxVar4;
	private javax.swing.JComboBox jComboBoxVar5;
	private javax.swing.JComboBox jComboBoxVar6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JProgressBar jProgressBar1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JSplitPane jSplitPane1;
	private javax.swing.JTextArea jTextAreaResults;
	private javax.swing.JTextField jTextFieldValue;
	private javax.swing.JTextField jTextFieldValue1;
	private javax.swing.JTextField jTextFieldValue2;
	private javax.swing.JTextField jTextFieldValue3;
	private javax.swing.JTextField jTextFieldValue4;
	private javax.swing.JTextField jTextFieldValue5;
	private javax.swing.JTextField jTextFieldValue6;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JMenuItem openMenuItem;
	// End of variables declaration//GEN-END:variables

	JComboBox vars[], ops[];
	JTextField vals[];
	JComboBox rel[];

}
